ReservationManagementApp/Models/Employee/EmployeeShiftModel.cs
using ReservationManagementApp.Models.Dto;
using System;
using System.Collections.Generic;

namespace ReservationManagementApp.Models.EmployeeShiftModel
{
    public class EmployeeShiftModel
    {
        public EmployeeShiftDto EmployeeShift { get; set; }
        public DateTime EndDate { get; set; }
        public IEnumerable<EmployeeShiftDto> EmployeeShiftsList { get; set; }


    }
}

ReservationManagementApp/Models/Employee/ServiceEmployeeModel.cs
using ReservationManagementApp.Models.Dto;
using System.Collections.Generic;

namespace ReservationManagementApp.Models.ServiceEmployeeModel
{
    public class ServiceEmployeeModel
    {
        public ServiceEmployeeDto ServiceEmployee { get; set; }
        public IEnumerable<ServiceEmployeeDto> ServicesEmployeesList { get; set; }

    }
}

ReservationManagementApp/Controllers/EmployeesShiftsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationManagementApp.Models;
using ReservationManagementApp.Models.EmployeeShiftModel;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class EmployeesShiftsController : Controller
    {
        private readonly ReservationManagementDbContext _context;

        public EmployeesShiftsController(ReservationManagementDbContext context)
        {
            _context = context;
        }

        // GET: EmployeesShifts
        public IActionResult Index(int? idEmployee, DateTime? workDay)
        {
            AddModelErrors();
            var employeesShiftsList = _context.EmployeesShifts.Where(elem => elem.IdEmployee == idEmployee
            && ((workDay != null && elem.WorkDay == workDay) || (workDay == null && elem.WorkDay >= DateTime.Today))).OrderBy(elem => elem.WorkDay).Include(e => e.IdEmployeeNavigation);
            EmployeeShiftModel employeeShiftModel = new EmployeeShiftModel();
            employeeShiftModel.EmployeeShiftsList = employeesShiftsList;
            employeeShiftModel.EmployeeShift = new EmployeesShifts();
            employeeShiftModel.EmployeeShift.IdEmployeeNavigation = _context.Employees.FirstOrDefault(elem => elem.Id == idEmployee.Value);
            employeeShiftModel.EmployeeShift.IdEmployee = idEmployee.Value;
            employeeShiftModel.EmployeeShift.WorkDay = workDay == null ? DateTime.Now : workDay.Value;
            employeeShiftModel.EndDate = workDay == null ? DateTime.Now : workDay.Value;

            return View(employeeShiftModel);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Filter(EmployeeShiftModel employeeShiftModel)
        {
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = employeeShiftModel.EmployeeShift.IdEmployee,
                workDay = employeeShiftModel.EmployeeShift.WorkDay
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult ClearFilter(EmployeeShiftModel employeeShiftModel)
        {
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = employeeShiftModel.EmployeeShift.IdEmployee
            });
        }


        // POST: EmployeesShifts/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(EmployeeShiftModel employeeShiftModel)
        {
            List<EmployeesShifts> allShiftsToAdd = GetShiftsForEmployee(employeeShiftModel);
            if (ValidateemployeeShiftModel(employeeShiftModel))
            {
                if (allShiftsToAdd.Count() > 0)//Validaciones
                {
                    foreach (EmployeesShifts shift in allShiftsToAdd)
                    {
                        if (ValidateShift(shift))
                        {
                            _context.Add(shift);
                        }
                        else
                        {
                            return RedirectToAction(nameof(Index), new
                            {
                                idEmployee = employeeShiftModel.EmployeeShift.IdEmployee
                            });
                        }
                    }
                    await _context.SaveChangesAsync();
                    return RedirectToAction(nameof(Index), new
                    {
                        idEmployee = employeeShiftModel.EmployeeShift.IdEmployee
                    });
                }
            }
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = employeeShiftModel.EmployeeShift.IdEmployee
            });
        }

        // GET: EmployeesShifts/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employeesShifts = await _context.EmployeesShifts
                .Include(e => e.IdEmployeeNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employeesShifts == null)
            {
                return NotFound();
            }

            return View(employeesShifts);
        }

        // POST: EmployeesShifts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            EmployeesShifts employeeShift = await _context.EmployeesShifts.FindAsync(id);
            if (employeeShift != null)
            {
                _context.EmployeesShifts.Remove(employeeShift);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = id
            });
        }

        private bool EmployeesShiftsExists(int id)
        {
            return _context.EmployeesShifts.Any(e => e.Id == id);
        }

        private List<EmployeesShifts> GetShiftsForEmployee(EmployeeShiftModel employeeShiftModel)
        {
            List<EmployeesShifts> employeesShifts = new List<EmployeesShifts>();
            var dates = new List<DateTime>();

            for (var dt = employeeShiftModel.EmployeeShift.WorkDay; dt <= employeeShiftModel.EndDate; dt = dt.AddDays(1))
            {
                dates.Add(dt);
            }

            foreach (DateTime date in dates)
            {
                EmployeesShifts employeeShift = new EmployeesShifts();
                employeeShift.InitHour = employeeShiftModel.EmployeeShift.InitHour;
                employeeShift.EndHour = employeeShiftModel.EmployeeShift.EndHour;
                employeeShift.WorkDay = date;
                employeeShift.IdEmployee = employeeShiftModel.EmployeeShift.IdEmployee;
                employeesShifts.Add(employeeShift);
            }
            return employeesShifts;
        }
        private bool ValidateemployeeShiftModel(EmployeeShiftModel employeeShiftModel)
        {
            if (employeeShiftModel.EmployeeShift.WorkDay > employeeShiftModel.EndDate)
            {
                TempData["ErrorDate"] = "The End Date must be greather than the Init Date";
            }
            if (employeeShiftModel.EmployeeShift.InitHour > employeeShiftModel.EmployeeShift.EndHour)
            {
                TempData["ErrorHours"] = "The End Date must be greather than the Init Date";
            }
            if (employeeShiftModel.EmployeeShift.InitHour > 24 || employeeShiftModel.EmployeeShift.InitHour < 0)
            {
                TempData["ErrorInitHour"] = "The Init Hour must be a number between 0 and 24";
            }
            if (employeeShiftModel.EmployeeShift.EndHour > 24 || employeeShiftModel.EmployeeShift.EndHour < 0)
            {
                TempData["ErrorEndHour"] = "The End Hour must be a number between 0 and 24";
            }
            if (employeeShiftModel.EmployeeShift.InitHour == employeeShiftModel.EmployeeShift.EndHour)
            {
                TempData["ErrorSameHour"] = "The init Hour must be different to End Hour";
            }
            if (TempData.Count > 0)
                return false;
            return true;
        }

        private void AddModelErrors()
        {
            if (TempData["ErrorDate"] != null && !String.IsNullOrEmpty(TempData["ErrorDate"].ToString()))
                ModelState.AddModelError("ErrorDate", TempData["ErrorDate"].ToString());
            if (TempData["ErrorHours"] != null && !String.IsNullOrEmpty(TempData["ErrorHours"].ToString()))
                ModelState.AddModelError("ErrorHours", TempData["ErrorHours"].ToString());
            if (TempData["InitEndHour"] != null && !String.IsNullOrEmpty(TempData["InitEndHour"].ToString()))
                ModelState.AddModelError("InitEndHour", TempData["InitEndHour"].ToString());
            if (TempData["ErrorEndHour"] != null && !String.IsNullOrEmpty(TempData["ErrorEndHour"].ToString()))
                ModelState.AddModelError("ErrorEndHour", TempData["ErrorEndHour"].ToString());
            if (TempData["Error"] != null && !String.IsNullOrEmpty(TempData["Error"].ToString()))
                ModelState.AddModelError("Error", TempData["Error"].ToString());
            if (TempData["ErrorSameHour"] != null && !String.IsNullOrEmpty(TempData["ErrorSameHour"].ToString()))
                ModelState.AddModelError("ErrorSameHour", TempData["ErrorSameHour"].ToString());
            TempData.Clear();
        }
        private bool ValidateShift(EmployeesShifts shift)
        {
            if (_context.EmployeesShifts.FirstOrDefault(elem => elem.IdEmployee == shift.IdEmployee
             && elem.WorkDay == shift.WorkDay
             && ((elem.InitHour < shift.InitHour && elem.EndHour > shift.InitHour)
             || (elem.InitHour < shift.EndHour && elem.EndHour > shift.EndHour)
             || (elem.InitHour == shift.InitHour && elem.EndHour <= shift.EndHour)
             || (elem.InitHour >= shift.InitHour && elem.EndHour <= shift.EndHour)
             || (elem.InitHour > shift.InitHour && elem.EndHour < shift.EndHour))
            ) != null)
            {
                TempData["Error"] = "The shift " + shift.InitHour + " - " + shift.EndHour + " is already included on day " + shift.WorkDay;
                return false;
            }
            return true;
        }
    }
}

ReservationManagementApp/Controllers/ServicesEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationManagementApp.Models;
using ReservationManagementApp.Models.ServiceEmployeeModel;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class ServicesEmployeesController : Controller
    {
        private readonly ReservationManagementDbContext _context;

        public ServicesEmployeesController(ReservationManagementDbContext context)
        {
            _context = context;
        }

        // GET: ServicesEmployees
        public IActionResult Index(int? idEmployee)
        {
            if (TempData["Error"] != null && !String.IsNullOrEmpty(TempData["Error"].ToString()))
                ModelState.AddModelError("Error", TempData["Error"].ToString());
            TempData.Clear();
            var servicesEmployeesList = _context.ServicesEmployees.Where(elem => elem.IdEmployee == idEmployee).Include(s => s.IdEmployeeNavigation).Include(s => s.IdServiceNavigation);
            ViewData["IdService"] = new SelectList(_context.Services, "Id", "Name");
            ServiceEmployeeModel serviceEmployeeModel = new ServiceEmployeeModel();
            serviceEmployeeModel.ServicesEmployeesList = servicesEmployeesList;
            serviceEmployeeModel.ServiceEmployee = new ServicesEmployees();
            serviceEmployeeModel.ServiceEmployee.IdEmployeeNavigation = _context.Employees.FirstOrDefault(elem => elem.Id == idEmployee.Value);
            serviceEmployeeModel.ServiceEmployee.IdEmployee = idEmployee.Value;
            return View(serviceEmployeeModel);
        }

        // POST: ServicesEmployees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceEmployeeModel serviceEmployeeModel)
        {
            ServicesEmployees serviceEmployee = new ServicesEmployees();
            serviceEmployee.IdEmployee = serviceEmployeeModel.ServiceEmployee.IdEmployee;
            serviceEmployee.IdService = serviceEmployeeModel.ServiceEmployee.IdService;
            if (_context.ServicesEmployees.FirstOrDefault(elem => elem.IdEmployee == serviceEmployee.IdEmployee && elem.IdService == serviceEmployee.IdService) != null)
            {
                TempData["Error"] = "This services is assigned";
                return RedirectToAction(nameof(Index), new
                {
                    idEmployee = serviceEmployee.IdEmployee
                });
            }
            if (serviceEmployeeModel.ServiceEmployee.IdService != 0)
            {
                _context.Add(serviceEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new
                {
                    idEmployee = serviceEmployee.IdEmployee
                });
            }

            ViewData["IdService"] = new SelectList(_context.Services, "Id", "Name", serviceEmployee.IdService);
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = serviceEmployee.IdEmployee
            });
        }

        // GET: ServicesEmployees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var serviceEmployee = await _context.ServicesEmployees
                .Include(r => r.IdEmployeeNavigation)
                .Include(r => r.IdServiceNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serviceEmployee == null)
            {
                return NotFound();
            }

            return View(serviceEmployee);
        }


        // POST: ServicesEmployees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var serviceEmployee = await _context.ServicesEmployees.FindAsync(id);
            if (serviceEmployee != null)
            {
                _context.ServicesEmployees.Remove(serviceEmployee);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = serviceEmployee.IdEmployee
            });
        }

        private bool ServicesEmployeesExists(int id)
        {
            return _context.ServicesEmployees.Any(e => e.Id == id);
        }
    }
}

ReservationManagementApp/Views/Employees/Create.cshtml
@model ReservationManagementApp.Models.Dto.EmployeeDto

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Employees</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname2" class="control-label"></label>
                <input asp-for="Surname2" class="form-control" />
                <span asp-validation-for="Surname2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCard" class="control-label"></label>
                <input asp-for="IdCard" class="form-control" />
                <span asp-validation-for="IdCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

ReservationManagementApp/Views/Employees/Delete.cshtml
@model ReservationManagementApp.Models.Dto.EmployeeDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employees</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCard)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ReservationManagementApp/Views/Employees/Details.cshtml
@model ReservationManagementApp.Models.Dto.EmployeeDto

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Employees</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Name)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Surname2)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Surname2)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.IdCard)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdCard)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.Id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ReservationManagementApp/Views/Employees/Edit.cshtml
@model ReservationManagementApp.Models.Dto.EmployeeDto

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Employees</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Id" />
            <div class="form-group">
                <label asp-for="Name" class="control-label"></label>
                <input asp-for="Name" class="form-control" />
                <span asp-validation-for="Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname" class="control-label"></label>
                <input asp-for="Surname" class="form-control" />
                <span asp-validation-for="Surname" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Surname2" class="control-label"></label>
                <input asp-for="Surname2" class="form-control" />
                <span asp-validation-for="Surname2" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="IdCard" class="control-label"></label>
                <input asp-for="IdCard" class="form-control" />
                <span asp-validation-for="IdCard" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
    <div class="col-md-4">
        <a asp-controller="ServicesEmployees" asp-action="Index" asp-route-idEmployee=@Model.Id>Services Management</a>
    </div>
    <div class="col-md-4">
        <a asp-controller="EmployeesShifts" asp-action="Index" asp-route-idEmployee=@Model.Id>Shifts Management</a>
    </div>
</div>
<div>
    <a asp-action="Index">Back to List</a>
</div>

ReservationManagementApp/Views/Employees/Index.cshtml
@model IEnumerable<ReservationManagementApp.Models.Dto.EmployeeDto>

@{
    ViewData["Title"] = "Index";
}

<h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Surname2)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.IdCard)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Name)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Surname2)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdCard)
                </td>
                <td>
                    <a asp-action="Edit" asp-route-id="@item.Id">Edit</a> |
                    <a asp-action="Details" asp-route-id="@item.Id">Details</a> |
                    <a asp-controller="EmployeesShifts" asp-action="Index" asp-route-idEmployee=@item.Id>Shift</a> |
                    <a asp-controller="ServicesEmployees" asp-action="Index" asp-route-idEmployee=@item.Id>Services</a> |
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>