ReservationManagementApp/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationManagementApp.Models;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class EmployeesController : Controller
    {
        private readonly ReservationManagementDbContext _context;

        public EmployeesController(ReservationManagementDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Surname2,IdCard")] Employees employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Edit), new
                {
                    id = employee.Id
                });

            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Surname2,IdCard")] Employees employees)
        {
            if (id != employees.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeesExists(employees.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Employees employee = _context.Employees.Where(elem => elem.Id == id).Include(s => s.Reservations).Include(s => s.ServicesEmployees).Include(s => s.EmployeesShifts).FirstOrDefault();
            if (employee != null)
            {
                foreach (Reservations reservation in employee.Reservations)
                {
                    _context.Reservations.Remove(reservation);
                }
                foreach (ServicesEmployees service in employee.ServicesEmployees)
                {
                    _context.ServicesEmployees.Remove(service);
                }
                foreach (EmployeesShifts shift in employee.EmployeesShifts)
                {
                    _context.EmployeesShifts.Remove(shift);
                }

                _context.Employees.Remove(employee);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeesExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

ReservationManagementApp/Controllers/ServicesEmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationManagementApp.Models;
using ReservationManagementApp.Models.ServiceEmployeeModel;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class ServicesEmployeesController : Controller
    {
        private readonly ReservationManagementDbContext _context;

        public ServicesEmployeesController(ReservationManagementDbContext context)
        {
            _context = context;
        }

        // GET: ServicesEmployees
        public IActionResult Index(int? idEmployee)
        {
            if (TempData["Error"] != null && !String.IsNullOrEmpty(TempData["Error"].ToString()))
                ModelState.AddModelError("Error", TempData["Error"].ToString());
            TempData.Clear();
            var servicesEmployeesList = _context.ServicesEmployees.Where(elem => elem.IdEmployee == idEmployee).Include(s => s.IdEmployeeNavigation).Include(s => s.IdServiceNavigation);
            ViewData["IdService"] = new SelectList(_context.Services, "Id", "Name");
            ServiceEmployeeModel serviceEmployeeModel = new ServiceEmployeeModel();
            serviceEmployeeModel.ServicesEmployeesList = servicesEmployeesList;
            serviceEmployeeModel.ServiceEmployee = new ServicesEmployees();
            serviceEmployeeModel.ServiceEmployee.IdEmployeeNavigation = _context.Employees.FirstOrDefault(elem => elem.Id == idEmployee.Value);
            serviceEmployeeModel.ServiceEmployee.IdEmployee = idEmployee.Value;
            return View(serviceEmployeeModel);
        }

        // POST: ServicesEmployees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(ServiceEmployeeModel serviceEmployeeModel)
        {
            ServicesEmployees serviceEmployee = new ServicesEmployees();
            serviceEmployee.IdEmployee = serviceEmployeeModel.ServiceEmployee.IdEmployee;
            serviceEmployee.IdService = serviceEmployeeModel.ServiceEmployee.IdService;
            if (_context.ServicesEmployees.FirstOrDefault(elem => elem.IdEmployee == serviceEmployee.IdEmployee && elem.IdService == serviceEmployee.IdService) != null)
            {
                TempData["Error"] = "This services is assigned";
                return RedirectToAction(nameof(Index), new
                {
                    idEmployee = serviceEmployee.IdEmployee
                });
            }
            if (serviceEmployeeModel.ServiceEmployee.IdService != 0)
            {
                _context.Add(serviceEmployee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index), new
                {
                    idEmployee = serviceEmployee.IdEmployee
                });
            }

            ViewData["IdService"] = new SelectList(_context.Services, "Id", "Name", serviceEmployee.IdService);
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = serviceEmployee.IdEmployee
            });
        }

        // GET: ServicesEmployees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var serviceEmployee = await _context.ServicesEmployees
                .Include(r => r.IdEmployeeNavigation)
                .Include(r => r.IdServiceNavigation)
                .FirstOrDefaultAsync(m => m.Id == id);
            if (serviceEmployee == null)
            {
                return NotFound();
            }

            return View(serviceEmployee);
        }


        // POST: ServicesEmployees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var serviceEmployee = await _context.ServicesEmployees.FindAsync(id);
            if (serviceEmployee != null)
            {
                _context.ServicesEmployees.Remove(serviceEmployee);
                await _context.SaveChangesAsync();
            }
            return RedirectToAction(nameof(Index), new
            {
                idEmployee = serviceEmployee.IdEmployee
            });
        }

        private bool ServicesEmployeesExists(int id)
        {
            return _context.ServicesEmployees.Any(e => e.Id == id);
        }
    }
}

ReservationManagementApp/Views/EmployeesShifts/Delete.cshtml
@model ReservationManagementApp.Models.Dto.EmployeeShiftDto

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Employee Shift</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            Work Day
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.WorkDay)
        </dd>
        <dt class="col-sm-2">
            Init Hour
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.InitHour)
        </dd>
        <dt class="col-sm-2">
            End Hour
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.EndHour)
        </dd>
        <dt class="col-sm-2">
            Employee @Html.DisplayNameFor(model => model.IdEmployeeNavigation.Name)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.IdEmployeeNavigation.Name)
        </dd>
    </dl>

    <form asp-action="Delete">
        <input type="hidden" asp-for="Id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index" asp-route-idEmployee="@Model.IdEmployee">Back to Shifts Management</a>
    </form>
</div>

ReservationManagementApp/Views/EmployeesShifts/Index.cshtml
@model ReservationManagementApp.Models.EmployeeShiftModel.EmployeeShiftModel

@{
    ViewData["Title"] = "Index";
}

<h1>Employee Shifts Management</h1>

<form asp-action="Create">
    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
    <div class="row">
        <div class="col-md-4">
            <div class="form-group">
                <label asp-for="EmployeeShift.IdEmployeeNavigation.Name" class="control-label"></label>
                <input asp-for="EmployeeShift.IdEmployeeNavigation.Name" class="form-control" disabled="disabled" />
                <input asp-for="EmployeeShift.IdEmployee" class="form-control" hidden="hidden" />
            </div>
        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">Work Day</label>
                <input id="initDate" type="date" asp-for="EmployeeShift.WorkDay" class="form-control" onchange="hideMessageError()" />
                <span asp-validation-for="EmployeeShift.WorkDay" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label class="control-label">Init Hour</label>
                <input asp-for="EmployeeShift.InitHour" class="form-control" onchange="hideMessageError()" />
                <span asp-validation-for="EmployeeShift.InitHour" class="text-danger"></span>
            </div>

        </div>
        <div class="col-md-4">
            <div class="form-group">
                <label class="control-label">End Date</label>
                <input id="endDate" type="date" asp-for="EndDate" class="form-control" onchange="hideMessageError()" />
            </div>
            <div class="form-group">
                <label class="control-label">End Hour</label>
                <input asp-for="EmployeeShift.EndHour" class="form-control" onchange="hideMessageError()" />
                <span asp-validation-for="EmployeeShift.EndHour" class="text-danger"></span>
            </div>
        </div>
        <div id="messageError" class="text-danger">
            @if (ViewData.ModelState["ErrorDate"] != null)
            {
                @Html.ValidationMessage("ErrorDate")
                <br />
            }
            @if (ViewData.ModelState["ErrorHours"] != null)
            {
                @Html.ValidationMessage("ErrorHours")
                <br />
            }
            @if (ViewData.ModelState["ErrorSameHour"] != null)
            {
                @Html.ValidationMessage("ErrorSameHour")
                <br />
            }
            @if (ViewData.ModelState["ErrorInitHour"] != null)
            {
                @Html.ValidationMessage("ErrorInitHour")
                <br />
            }
            @if (ViewData.ModelState["ErrorEndHour"] != null)
            {
                @Html.ValidationMessage("ErrorEndHour")
                <br />
            }
            @if (ViewData.ModelState["Error"] != null)
            {
                @Html.ValidationMessage("Error")
                <br />
            }
        </div>
    </div>
    <div class="form-group">
        <div class="form-group">
            <input type="submit" value="Add" class="btn btn-primary" />
        </div>
    </div>
</form>
<div class="row">
    <div class="col-md-4">
        <a asp-controller="Employees" asp-action="Index">Back to list</a>
    </div>
    <div class="col-md-4">
        <a asp-controller="Employees" asp-action="Edit" asp-route-id=@Model.EmployeeShift.IdEmployee>Edit Employee</a>
    </div>
    <div class="col-md-4">
        <a asp-controller="ServicesEmployees" asp-action="Index" asp-route-idEmployee=@Model.EmployeeShift.IdEmployee>Services Management</a>
    </div>
</div>
<br />

<hr />
<h4>Employee Shifts</h4>
<hr />
<h6>Filter Search</h6>

<div class="row">
    <div class="col-md-11">
        <form asp-action="Filter">
            <div class="row">
                <div class="col-md-2">
                    <label class="control-label">Work Day</label>
                </div>
                <div class="col-md-9">
                    <input type="date" asp-for="EmployeeShift.WorkDay" class="form-control" />
                    <input asp-for="EmployeeShift.IdEmployee" class="form-control" hidden="hidden" />
                </div>
                <div class="col-md-1">
                    <input type="submit" value="Filter" class="btn btn-primary" />
                </div>
            </div>
        </form>
    </div>
    <div class="col-md-1">
        <form asp-action="ClearFilter">
            <input asp-for="EmployeeShift.IdEmployee" class="form-control" hidden="hidden" />
            <div class="form-group">
                <input type="submit" value="Clear" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>
<table class="table">
    <thead>
        <tr>
            <th>
                Work Day
            </th>
            <th>
                Init Hour
            </th>
            <th>
                End Hour
            </th>
            <th>
                Employee Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model.EmployeeShiftsList)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.WorkDay)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.InitHour)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.EndHour)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.IdEmployeeNavigation.Name)
                </td>
                <td>
                    <a asp-action="Delete" asp-route-id="@item.Id">Delete</a>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    window.onload = function () {
        document.getElementById("initDate").setAttribute('min', new Date().toISOString().split('T')[0]);
        document.getElementById("endDate").setAttribute('min', new Date().toISOString().split('T')[0]);
    };
    function hideMessageError() {
        document.getElementById('messageError').style.visibility = "hidden";
    }
</script>