ReservationManagementApp/Controllers/EmployeesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ReservationManagementApp.Models;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class EmployeesController : Controller
    {
        private readonly ReservationManagementDbContext _context;

        public EmployeesController(ReservationManagementDbContext context)
        {
            _context = context;
        }

        // GET: Employees
        public async Task<IActionResult> Index()
        {
            return View(await _context.Employees.ToListAsync());
        }

        // GET: Employees/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employee == null)
            {
                return NotFound();
            }

            return View(employee);
        }

        // GET: Employees/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Employees/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Surname,Surname2,IdCard")] Employees employee)
        {
            if (ModelState.IsValid)
            {
                _context.Add(employee);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Edit), new
                {
                    id = employee.Id
                });

            }
            return View(employee);
        }

        // GET: Employees/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employee = await _context.Employees.FindAsync(id);
            if (employee == null)
            {
                return NotFound();
            }
            return View(employee);
        }

        // POST: Employees/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Surname,Surname2,IdCard")] Employees employees)
        {
            if (id != employees.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(employees);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!EmployeesExists(employees.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(employees);
        }

        // GET: Employees/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var employees = await _context.Employees
                .FirstOrDefaultAsync(m => m.Id == id);
            if (employees == null)
            {
                return NotFound();
            }

            return View(employees);
        }

        // POST: Employees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public IActionResult DeleteConfirmed(int id)
        {
            Employees employee = _context.Employees.Where(elem => elem.Id == id).Include(s => s.Reservations).Include(s => s.ServicesEmployees).Include(s => s.EmployeesShifts).FirstOrDefault();
            if (employee != null)
            {
                foreach (Reservations reservation in employee.Reservations)
                {
                    _context.Reservations.Remove(reservation);
                }
                foreach (ServicesEmployees service in employee.ServicesEmployees)
                {
                    _context.ServicesEmployees.Remove(service);
                }
                foreach (EmployeesShifts shift in employee.EmployeesShifts)
                {
                    _context.EmployeesShifts.Remove(shift);
                }

                _context.Employees.Remove(employee);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

        private bool EmployeesExists(int id)
        {
            return _context.Employees.Any(e => e.Id == id);
        }
    }
}

ReservationManagementApp/Controllers/ServicesController.cs
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System.IO;
using Microsoft.AspNetCore.Http;
using Microsoft.Extensions.Configuration;
using ReservationManagementApp.ServicesApp;
using Newtonsoft.Json;
using ReservationManagementApp.Models.Dto;

namespace ReservationManagementApp.Controllers
{
    [Authorize(Policy = "Admin")]
    public class ServicesController : Controller
    {
        private readonly IConfiguration _configuration;
        public HttpServicesReponse _clientService = new HttpServicesReponse();
        public ServicesController(IConfiguration configuration)
        {
            this._configuration = configuration;
        }

        // GET: Services
        public IActionResult Index()
        {
            string responseBody = this._clientService.GetResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi").GetAwaiter().GetResult();
            List<ServiceDto> list = JsonConvert.DeserializeObject<List<ServiceDto>>(responseBody);
            return View(list);
        }

        // GET: Services/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }
            string responseBody = await this._clientService.GetResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id);
            ServiceDto service = JsonConvert.DeserializeObject<ServiceDto>(responseBody);
            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // GET: Services/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Services/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Id,Name,Price,Image,Description")] ServiceDto service, [FromForm] IFormFile image)
        {
            if (ModelState.IsValid)
            {
                if (image != null)
                {
                    //upload files to wwwroot
                    var fileName = Path.GetFileName(image.FileName);
                    var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/wwwroot/Resources/", "Images", fileName);
                    service.Image = "/Resources/Images/" + fileName;
                    using (var fileSteam = new FileStream(filePath, FileMode.Create))
                    {
                        await image.CopyToAsync(fileSteam);
                    }
                }
                string responseBody = this._clientService.PostResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi", JsonConvert.SerializeObject(service)).GetAwaiter().GetResult();
                if (!string.IsNullOrEmpty(responseBody))
                    return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string responseBody = await this._clientService.GetResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id);
            ServiceDto service = JsonConvert.DeserializeObject<ServiceDto>(responseBody);
            TempData["Image"] = service.Image;
            if (service == null)
            {
                return NotFound();
            }
            return View(service);
        }

        // POST: Services/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Id,Name,Price,Image,Description")] ServiceDto service, IFormFile image)
        {
            if (id != service.Id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    if (image != null)
                    {
                        //upload files to wwwroot
                        var fileName = Path.GetFileName(image.FileName);
                        var filePath = Path.Combine(Directory.GetCurrentDirectory() + "/wwwroot/Resources/", "Images", fileName);
                        service.Image = "/Resources/Images/" + fileName;
                        using (var fileSteam = new FileStream(filePath, FileMode.Create))
                        {
                            await image.CopyToAsync(fileSteam);
                        }
                        TempData.Remove("Image");
                    }
                    else if (TempData["Image"] != null)
                    {
                        service.Image = TempData["Image"].ToString();
                        TempData.Remove("Image");
                    }
                    string responseBody = this._clientService.PutResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id, JsonConvert.SerializeObject(service)).GetAwaiter().GetResult();

                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ServicesExists(service.Id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(service);
        }

        // GET: Services/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            string responseBody = await this._clientService.GetResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id);
            ServiceDto service = JsonConvert.DeserializeObject<ServiceDto>(responseBody);

            if (service == null)
            {
                return NotFound();
            }

            return View(service);
        }

        // POST: Services/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            await this._clientService.DeleteResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id);
            return RedirectToAction(nameof(Index));

        }

        private bool ServicesExists(int id)
        {
            string responseBody = this._clientService.GetResponse(this._configuration["AppSettings:ApiRest"] + "api/ServiceApi/" + id).GetAwaiter().GetResult();
            ServiceDto service = JsonConvert.DeserializeObject<ServiceDto>(responseBody);
            return service != null;
        }

    }
}

ReservationManagementApp/Views/Shared/_CurrentsReservationsEmployee.cshtml
@model IEnumerable<ReservationManagementApp.Models.Dto.ReservationDto>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    Employee @Html.DisplayNameFor(model => model.IdEmployeeNavigation.Name)
                </th>
                <th>
                    Service  @Html.DisplayNameFor(model => model.IdServiceNavigation.Name)
                </th>
                <th>
                    Service  @Html.DisplayNameFor(model => model.IdServiceNavigation.Image)
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdEmployeeNavigation.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdServiceNavigation.Name)
                    </td>
                    <td>
                        @if (item.IdServiceNavigation.Image != null)
                        {
                            <img class="zoom" src="@item.IdServiceNavigation.Image" alt="Image" />
                        }
                        else
                        {
                            <img class="zoom" src="~/Resources/Images/not-available.png" alt="Image" />
                        }

                    </td>
                    <td>
                        <form asp-action="Create">
                            <input hidden="hidden" name="IdEmployee" value="@item.IdEmployee" />
                            <input hidden="hidden" name="IdService" value="@item.IdService" />
                            <input hidden="hidden" type="datetime" name="Date" value="@item.Date" />
                            <input type="submit" value="Make a Reservation" />
                        </form>
                    </td>
                </tr>
            }
        </tbody>
    </table>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />

}

ReservationManagementApp/Views/Shared/_CurrentsReservationsUser.cshtml
@model IEnumerable<ReservationManagementApp.Models.Dto.ReservationDto>

@if (Model.Count() > 0)
{
    <table class="table">
        <thead>
            <tr>
                <th>
                    @Html.DisplayNameFor(model => model.Date)
                </th>
                <th>
                    Employee @Html.DisplayNameFor(model => model.IdEmployeeNavigation.Name)
                </th>
                <th>
                    Service  @Html.DisplayNameFor(model => model.IdServiceNavigation.Name)
                </th>
                <th>
                    Action
                </th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.Date)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdEmployeeNavigation.Name)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.IdServiceNavigation.Name)
                    </td>
                    <td>
                        <a asp-action="Delete" asp-route-id="@item.Id">Cancel</a>
                    </td>

                </tr>
            }
        </tbody>
    </table>
}

ReservationManagementApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ReservationManagementApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">ReservationManagementApp</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Reservations" asp-action="Index">Reservation</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Services" asp-action="Index">Services</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Employees" asp-action="Index">Employees</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2020 - ReservationManagementApp</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>